version: "3.9"
services:
  nodejs:
    build: ./node 
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  mongodb:
    build: ./mongodb
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD} 
volumes:
  mongodb:
