version: "3.9"
services:
  nodejs:
    build: ./node 
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      API_KEY: ${API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  mongodb:
    build: ./mongodb
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD} 
volumes:
  mongodb:
